### ISSUE TITLE
registerCapability not working

### ISSUE THREAD

**Issue by A-Kvisgaard** [athombv/node-homey-meshdriver#187]
Hi,
I’m trying to write a driver app for a Zigbee CO2, Humidity & Temperature sensor from [Titan Products](https://www.titanproducts.com/sensors-hvac-and-bms-peripherals/wireless-sensors/zigbee-3-0-wireless-sensors/zigbee-room-co2-humidity-temperature-sensor.html). To do so, I have used this library. I have been able to connect to the sensor and get a [Print of the clusters](https://pastebin.com/e18f7uLu). But when I try to register the Capability to the cluster it does not display those values.  

Custom Capability
```JSON
"temperature": {
      "type": "number",
      "title": {
        "en": "Temperature"
      },
      "uiComponent": "sensor",
      "getable": true,
      "setable": false,
      "icon": "assets/temperature.svg"
    }
```
In Device.js onMeshInit:
```JavaScript
this.registerCapability("temperature", 'msTemperatureMeasurement', {
    report: 'measuredValue',
    reportParser: value => value / 1000,
    get: 'measuredValue',
    getParser: value => value / 1000,
});
```

![image](https://user-images.githubusercontent.com/35926878/86763876-f0008b80-c047-11ea-843a-49058c7e2c72.png)

Just to test I set up an attributeReportListener where I get the desired output:
```JavaScript
this.registerAttrReportListener(
            'msTemperatureMeasurement',
            'measuredValue',
            60,
            300,
            50,
            this.onTemperatureMeasurementReport.bind(this))
            .then(() => {
                this.log('registered attr report listener');
            })
            .catch(err => {
                this.error('failed to register attr report listener', err);
            });

onTemperatureMeasurementReport(value){
        this.log('Temperature: ', value / 100);
    }
```
**Output:** 
2020-07-07 11:45:37 [log] [ManagerDrivers] [co2th] [0] registerAttrReportListener() -> configured attr reporting attrReport_0_msTemperatureMeasurement_measuredValue
2020-07-07 11:45:37 [log] [ManagerDrivers] [co2th] [0] registered attr report listener
2020-07-07 11:47:37 [log] [ManagerDrivers] [co2th] [0] Temperature:  23.35
2020-07-07 11:48:37 [log] [ManagerDrivers] [co2th] [0] Temperature:  23.31
2020-07-07 11:50:37 [log] [ManagerDrivers] [co2th] [0] Temperature:  23.28

What might I be doing wrong?

**Comment by A-Kvisgaard** [comment]
Sorry to reopen this issue, I closed it prematurely. 
I've changed the capabilities to the default for CO2, humidity, and temperature, but with the same result:

![image](https://user-images.githubusercontent.com/35926878/88819740-af1c1280-d1c0-11ea-8d94-c81d38f73e69.png)

app.json

```JSON
"capabilities": [
        "onoff",
        "measure_co2",
        "measure_humidity",
        "measure_temperature" ],
```

device.js

```JavaScript
this.registerCapability("measure_co2","1037", {
            get: "2",
            getParser:  value => value * 100000,
            report: "2",
            reportParser: value => value * 10000
        });

        this.registerCapability("measure_humidity", 'msRelativeHumidity', {
            report: 'measuredValue',
            reportParser: value => value / 1000,
            get: 'measuredValue',
            getParser: value => value / 1000
        });

        this.registerCapability("measure_temperature","msTemperatureMeasurement", {
            report: 'measuredValue',
            reportParser: value => value / 100,
            get: 'measuredValue',
            getParser: value => value / 100
        });
```

**Comment by RobinBol** [comment]
`this.registerCapability("measure_co2","1037"`: this will not work, "1037" is not a supported cluster
for the other two;
```
this.registerCapability("measure_humidity", 'msRelativeHumidity');
this.registerCapability("measure_temperature","msTemperatureMeasurement");
```
should be enough.

Please note that we are in the process of releasing a major Zigbee update which requires you to create Zigbee apps using SDK v3 only. I will add you to the #zigbee channel on our community Slack where people can assist you with this.
