### ISSUE TITLE
Add configurable timeout for ZigBeeCluster attr read

### ISSUE THREAD

**Issue by rogro82** [athombv/node-homey-meshdriver#21]
The current ZigBeeCluster read function (for reading attributes) has no time-out so basically it waits indefinitely instead of throwing an exception.

I want to poll onoff to see if a lamp has been turned on/off and still can be reached ( and has not been powered off completely ). Because the current read function does not time-out it also can't be used to send a dummy off-report or anything (e.g. in catch).

I have fixed this locally by adding a Promise.race in _getCapabilityValue and a configurable getTimeout and getError ( to report ) in getOpts, but I dont know if there is already a better way of handling ZigBee read time-outs. Perhaps it would be better to add a time-out property to the function itself.

**Comment by RobinBol** [comment]
I am a bit hesitant to add a timeout for the read method itself, as battery devices will respond but after an unknown delay. Best would be to write a wrapper around the ZigBeeCluster read function which will add a configurable timeout after which the read is rejected.

**Comment by RobinBol** [comment]
Closing since homey-meshdriver has since been replaced with [homey-zwavedriver](https://github.com/athombv/node-homey-zwavedriver) and [homey-zigbeedriver](https://github.com/athombv/node-homey-zigbeedriver). Thanks for reporting!
