### ISSUE TITLE
FlowCardAction('').register(); not working for system_device's

### ISSUE THREAD

**Issue by caseda** [athombv/node-homey-meshdriver#52]
homey fw: 1.5.6 RC7
node-homey-meshdriver: 1.2.4 (latest)

in this particular case the register() for the resetMeter card is not activating, and thus will not register the flow card.
this will be most likely for all the registers in the system expand drivers, so something is wrong in the core.

as soon as i transfer the code (1:1) to my own driver in the meshinit() it works.

https://github.com/athombv/homey/issues/2128 is related so you may close this, though it is most likely not just for meteringDevices, leaving this at least for the extra information.

Small update:
seems like i can't get any logging out of it when trying to change things up a little, might have the same reason?

**Comment by RobinBol** [comment]
Thanks for reporting, thought of this myself as well a while back, the approach is wrong. Did not find the time to look at a fix though. The FlowCard should actually be registered in `app.js` but not sure how to handle the inheritance then...

**Comment by RobinBol** [comment]
Seems like this issue is outdated momentarily, since the built-in meter reset flow card has been deprecated. If I misinterpret your issue please let me know.
