### ISSUE TITLE
Fishy code in ZwaveDevice.configurationSet

### ISSUE THREAD

**Issue by Thorarin** [athombv/node-homey-meshdriver#81]
I've noticed a bit of a code smell in the `configurationSet` method of the `ZwaveDevice` class.

For battery powered devices, an already resolved promise is returned. Then when the CONFIGURATION_SET actually succeeds, the same promise is resolved again, but now with a result. This is a no-op.

In any case, there currently doesn't seem to be a way to wait until a setting has been actually changed successfully, which happened to be something I wanted to do 🙁 I'm not certain what changing this would affect though. At the very least, I think the `onSettings` implementation would need to not await the `configurationSet` calls it makes.

On the whole, I'm not certain what the intention of the code is, but it's a bit dodgy 😃

**Comment by WeeJeWel** [comment]
I agree with your findings. Yet creating a promise that doesn't resolve for >15 mins also doesn't feel right.

What you could do is wait for the `online` event on the node if it isn't only already, and then set the configuration parameter.
