### ISSUE TITLE
Logged error "do not use getOnStart for battery devices, use getOnOnline instead"

### ISSUE THREAD

**Issue by Thorarin** [athombv/node-homey-meshdriver#82]
Quite a few capabilities have `getOnStart: true` defind as their default options. When that capability is registered by a battery device, there is an error message logged:
```
[err] [ManagerDrivers] [drivername] [0] do not use getOnStart for battery devices, use getOnOnline instead
```

There don't appear to be any adverse side effects, but to prevent the error message, an explicit `getOpts` would need to be set for each capability. Perhaps the error should not be logged if getOnStart is set implicitly from the system options?

PS: while investigating this issue, I ran into another bug as well. See PR https://github.com/athombv/node-homey-meshdriver/pull/83 for description and fix.

**Comment by RobinBol** [comment]
Not logging anything is not really desired, while it might not have any adverse side effects defining `getOnStart` on a battery device will result in putting a GET command in the send queue (so when the device comes online the GET will be sent). The developer should be aware of that, hence the logging. If you are developing for a battery device for which the `getOnStart` is not desired just override it.

(I do agree it should actually be a warning level log, not error)
